### PR TITLE
Fix missing link target

### LINKED ISSUE #596: Could not split link into name and target
Sentry Issue: [POSEIDON-5K](https://codeocean.sentry.io/issues/5210781378/?referrer=github_integration)

```
could not split link into name and target
```

This happened when we as administrators opened some data below `/proc`.

### PR DESCRIPTION
**Pull request by mpass99**
for listing the file system with a link, the executing user does not have enough privileges to read the target.

Closes #596

### CODE REVIEW

File: pkg/nullio/ls2json.go [hunk 1]
```diff
@@ -163,11 +163,14 @@ func (w *Ls2JsonWriter) parseFileHeader(matches [][]byte) ([]byte, error) {
...
 		const NumberOfPartsInALink = 2
-		if len(parts) == NumberOfPartsInALink {
+		switch len(parts) {
+		case NumberOfPartsInALink:
 			name = dto.FilePath(parts[0])
 			linkTarget = dto.FilePath(parts[1])
-		} else {
-			log.WithContext(w.sentrySpan.Context()).Error("could not split link into name and target")
+		case 1:
+			// This case happens when a user tries to read the target of a link without permission. See #596.
```
Comment (MrSerth) [inline pkg/nullio/ls2json.go:171]: We could improve the comment to notice that we don't do any action for such an entry (no op).

**Review by MrSerth — COMMENTED** [review]
Thanks, looks good! I tested the branch locally and can confirm that your patch resolves the issue for me.

There is one question left, though: When listing files where this (former) bug triggers, I still have an exit code 1 and thus the following warning: ` level=warning msg="Ignoring error of listing the file system" error="<nil>" exitCode=1 package=runner`. Do we just continue to ignore it (and log as warning) or do we want to do something special (since we know why the error was generated in the first place....)

**Review by MrSerth — APPROVED** [review]
Perfect, works like a charm. Thanks!

**Comment by MrSerth** [comment]
I've created an issue for the flaky unit test #669.

**Comment by MrSerth** [comment]
I've also amended ticket #623 for the failed e2e test. It seems like we need to investigate in the test suite, once again.
