### PR TITLE
Adjust Influxdb buffering

### LINKED ISSUE #479: Improve error handling for sending events to Influxdb
Recently, we lost some monitoring data (see #471 and #470) that were not sent to Influxdb. Besides improving the monitoring for system services (#471), we are also interested in understanding why we didn't see a Sentry event for Poseidon failing to send data to Influxdb.

Therefore, this ticket is about checking the Influxdb error handling in Poseidon.

### PR DESCRIPTION
**Pull request by mpass99**
as we have experienced silent package drops. This issue is not fixed, it is just made less probable.

Closes #479

### CODE REVIEW

File: pkg/monitoring/influxdb2_middleware.go [hunk 1]
```diff
@@ -57,18 +57,21 @@ func InitializeInfluxDB(db *config.InfluxDB) (cancel func()) {
 		return func() {}
 	}
 
+	// How often to retry to write data.
+	const maxRetries = 10
```
Comment (MrSerth) [inline pkg/monitoring/influxdb2_middleware.go:61]: Do you think we should increase the `maxRetries` as well? I am assuming that in the old version, we tried for a maximum of 30s * 10 = 300s = 5m, where we only retry 5s * 10 = 50s in the new version? Or are there some other implications I am not aware of?

Comment (MrSerth) [reply pkg/monitoring/influxdb2_middleware.go]: I see, that's indeed true -- the thin line is not easy to hit. Nevertheless, I think that the increased `maxRetries` is a good thing: Sometimes, an instance might just become unavailable for various reasons (such as a reboot). In such a case, 50 seconds should normally be enough to transmit data (even though I haven't measured the reboot times), but the margin would be somewhat small. Therefore, increasing it a little makes sense to me. I think, we should just try it with the new values and observe the difference in Sentry.
