### PR TITLE
#155 refactor and synchronise writing to CodeOcean.

### LINKED ISSUE #155: Sentry: Error writing the message
Part of #135

Sentry Issue: [POSEIDON-C](https://sentry.io/organizations/openhpi/issues/2815744101/?referrer=github_integration)

```
Error writing the message
error: "websocket: close sent"
```

### LINKED ISSUE #156: Sentry: Error reading client message
Part of #135

Sentry Issue: [POSEIDON-14](https://sentry.io/organizations/openhpi/issues/2895674796/?referrer=github_integration)

```
Error reading client message
error: websocket: close 1006 (abnormal closure): unexpected EOF
```

### PR DESCRIPTION
**Pull request by mpass99**
Closes #155 (Hopefully)
Closes #165

### CODE REVIEW

File: internal/api/ws/codeocean_writer.go [hunk 1]
```diff
@@ -0,0 +1,155 @@
...
+
+// WebSocketWriter is an interface that defines which data is required and which information can be passed.
+type WebSocketWriter interface {
+	StdOut() io.Writer
+	StdErr() io.Writer
+	SendExitInfo(info *runner.ExitInfo)
+}
+
+// codeOceanOutputWriter is a concrete WebSocketWriter implementation.
+// It forwards the data written to stdOut or stdIn (Nomad, AWS) to the WebSocket connection (CodeOcean).
```
Comment (MrSerth) [inline internal/api/ws/codeocean_writer.go:35]:
```suggestion
// It forwards the data written to stdOut or stdErr (Nomad, AWS) to the WebSocket connection (CodeOcean).
```

**Review by MrSerth — APPROVED** [review]
I took some time to review and hope that I got everything (for me, the input and output handling with the WebSocket connection and the loops is really an advanced topic). I appreciate that you separated the WebSocket components into an own package, this absolutely makes sense! Thanks for your efforts 👏
