### PR TITLE
Formalize Memory Monitoring

### LINKED ISSUE #452: Send (OOM) kills to Sentry
Currently, when Poseidon is killed, e.g., by the OOM killer, we do not get notified nor any Sentry event. Ideally, we would add some hook or other mechanism to get informed whenever Poseidon quits unexpectedly.

### PR DESCRIPTION
**Pull request by mpass99**
Closes #452 

by extracting the interval and threshold into configuration options.

Related to f670b07e.

### CODE REVIEW

File: cmd/poseidon/main.go [hunk 1]
```diff
@@ -112,18 +112,19 @@ func initProfiling(options config.Profiling) (cancel func()) {
...
-	// We assume that Poseidon usually takes about 50-300 MB of memory. Therefore, we specify the threshold of 1 GB.
-	// Improve: Make this value dynamic or relative.
-	const threshold = 1 * 1000 * 1000 * 1000
-	const interval = 5 * time.Second
+func watchMemoryAndAlert(options config.Profiling) {
+	if options.MemoryInterval == 0 {
+		return
+	}
 
+	var exceeded bool
```
Comment (MrSerth) [inline cmd/poseidon/main.go:120]: When is the value of this variable set? I see two usages below, but none of them changes the value. Am I missing something?

Comment (mpass99) [reply cmd/poseidon/main.go:120]: No, I missed adjusting its value. Thank you for catching that!

Comment (MrSerth) [reply cmd/poseidon/main.go:120]: Ah, okay. Now, it makes sense. You remember whether the last check already saw an exceeded memory use and each time this observation changes, you issue a corresponding message.

**Review by MrSerth — APPROVED** [review]
